version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: development
    reviewers: [ aaaaaaaalesha ]
    labels:
      - dependencies
      - automatic
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: development
    reviewers: [ aaaaaaaalesha ]
    labels:
      - dependencies
      - automatic
